name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Debug atau Release'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Grant execute permission
        run: chmod +x gradlew
      
      - name: Build APK
        run: |
          if [ "${{ inputs.build_variant }}" = "release" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/**/*.apk
